### ISSUE TITLE
Auf dem Weg zum 1. Tag

### ISSUE THREAD

**Issue by TanDro** [umit-iace/tool-libs#4]
Versuchsstände, die zu überarbeiten und auf den selben Stand zu bringen sind:

- [x] MobRost
- [ ] Segway @ditscheey 
- nTrailer (Kommunikation an Florian)
- [ ] longpipe @jhalmen 
- [x] Flachwasser @TanDro @jhalmen 
- [ ] anpama @ditscheey 
- [ ] kraftmesstand @kroni121

**Comment by jhalmen** [comment]
Flachwasser ist mit https://github.com/umit-iace/labor-flachwasser/pull/28 dann auch so weit
