### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by jhalmen** [umit-iace/tool-libs#99]
Zwecks der Namensgebung der backend-spezifischen Teile, was im `can`-branch nun nicht mehr drin war:

der Grund dafür, dass es überhaupt nötig ist Dinge umzubenennen, ist, dass linux selber schon einen header bringt, den man über `#include <linux/can.h>` benutzt, weswegen unsere implementierung der CAN-schnittstelle nicht unter `linux/can.h` liegen kann, und mir kein besserer Name einfällt als `linux/canimpl.h`.

Die derzeitige Idee ist, alles backend-spezifische unter `sys` zu inkludieren (also `sys/can.h`, aber auch `sys/gpio.h`, `sys/encoder.h`, usw. auf STM-seite), und den richtigen Ordner vom build-system wählen zu lassen.

Die Struktur sähe dann etwa folgendermaßen aus
```
tool-libs/
| linux/
| | sys/
| | | can.h
| | | host.h
| | host.cpp
| | CMakeLists.txt
| stm/
| | sys/
| | | adc.h
| | | can.h
| | | dma.h
| | | encoder.h
| | | gpio.h
| | | hal.h
| | | i2c.h
| | | pwm.h
| | | registry.h
| | | spi.h
| | | timer.h
| | | uart.h
| | | spi.h.bak
| | | uart.cpp.bak
| | can.cpp
| | hal.cpp
| | i2c.cpp
| | spi.cpp
| | uart.cpp
| | CMakeLists.txt
```

mit
```cmake
if( STM )
    add_subdirectory(stm)
else()
    add_subdirectory(linux)
endif()
```
im obersten CMakeLists.

Das Unangenehme wäre, dass alles was `tool-libs` verwendet angepasst werden muss, sozusagen einmal
`%s/linux\/\(.*\).h/sys\/\1.h/`
und 
`%s/stm\/\(.*\).h/sys\/\1.h/`
in vim ausfuehren

was hältst du davon?

**Comment by TanDro** [comment]
Klingt nach einem sehr guten Plan, bin dafür.
